version: "3.8"
services:
n8n:
image: n8nio/n8n
restart: unless-stopped
ports:
- "5678:5678"
environment:
- N8N_BASIC_AUTH_ACTIVE=true
- N8N_BASIC_AUTH_USER=user
- N8N_BASIC_AUTH_PASSWORD=password
- GENERIC_TIMEZONE=Asia/Colombo
- NODE_ENV=production
- N8N_SECURE_COOKIE=false
volumes:
- /home/peter/n8n_data:/home/node/.n8n
